site_name: Alpha.CA.gov handbook
site_url: https://handbook-cadotgov.readthedocs.io/en/latest/

repo_url: https://github.com/cagov/handbook-cadotgov/

theme:
    name: readthedocs

extra_css:
    - css/extra.css

plugins:
    - search

