site_name: Alpha.CA.gov handbook
site_url: https://handbook-cadotgov.readthedocs.io/en/latest/
repo_url: https://github.com/cagov/handbook-cadotgov/

pages:
    - Welcome: README.md
    - Assets: assets.md
    - test123: test123.md

theme:
    name: readthedocs

extra_css:
    - css/extra.css

plugins:
    - search
