site_name: Alpha.CA.gov handbook
site_url: https://handbook-cadotgov.readthedocs.io/en/latest/
repo_url: https://github.com/cagov/handbook-cadotgov/

pages:
    - Welcome: README.md
    - Ceremonies: Ceremonies.md
    - Daily-Standup: DailyStandup.md
    - Demos: Demos.md
    - Retrospectives: Retros.md
    - Sprint-Planning: Planning.md
    - Meeting-hygiene: Meetinghygiene.md

theme:
    name: readthedocs

extra_css:
    - css/extra.css

plugins:
    - search
