site_name: Alpha.CA.gov handbook
site_url: https://handbook.alpha.ca.gov/en/latest/
repo_url: https://github.com/cagov/handbook-cadotgov/

pages:
    - Welcome: README.md
    - Contributions: contributions.md
    - Operations: operations.md
    - Guiding principles: principles.md
    - Content guide: content.md
    - Design: design.md

theme:
    name: readthedocs

extra_css:
    - css/extra.css

plugins:
    - search
    
